# Dependabot configuration

version: 2
updates:
  # Manage Docker dependencies
  - package-ecosystem: "docker"
    versioning-strategy: "increase"  # Update to the latest version
    directory: /  # Location of the Dockerfile
    schedule:
      interval: "weekly"
  # Manage other package managers as needed.